[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
build_flags =
  -Ilib
  -DARDUINO_USB_MODE=0
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_HID_ON_BOOT=0
  -DUSB_MANUFACTURER=\"kiwifruit0\"
  -DUSB_PRODUCT=\"LoChord\"
  -DUSER_SETUP_LOADED=1
  -DST7789_DRIVER=1
  -DTFT_WIDTH=142
  -DTFT_HEIGHT=428
  -DTFT_MOSI=11
  -DTFT_SCLK=12
  -DTFT_CS=10
  -DTFT_DC=9
  -DTFT_RST=8
  -DTFT_MISO=-1
  -DSPI_FREQUENCY=40000000

[env:native]
platform = native
test_framework = unity
lib_deps =
  throwtheswitch/Unity@^2.6.1
build_flags = -Ilib
lib_extra_dirs = lib
