[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.extra_flags =
  -DARDUINO_USB_MODE=0
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DARDUINO_USB_HID_ON_BOOT=0
  -DUSB_MANUFACTURER=\"kiwifruit0\"
  -DUSB_PRODUCT=\"LoChord\"
build_flags =
  -Ilib

[env:native]
platform = native
test_framework = unity
lib_deps =
  throwtheswitch/Unity@^2.6.1
build_flags = -Ilib
lib_extra_dirs = lib
